package com.friendster.api.client.enums;

public enum RequestType {
	USER, SHOUTOUT, APP_FRIENDS, FRIENDS, SCORE, TOP_SCORES, SHOUTOUT_P, MESSAGES, MESSAGE, MESSAGE_P, NOTIFICATION_P, WALLET_BALANCE, WALLET_COMMIT, WALLET_GET, WALLET_CALLBACK, NEW_MESSAGES;
}
